version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /tmp/docker/volumes/mongodb:/data/db
#    networks:
#      - marcelbraghini
#
#  quarkus:
#    container_name: quarkus
#    build:
#      context: ./src/main/docker/
#      dockerfile: Dockerfile.native
#    depends_on:
#      - mongodb
#    networks:
#      - marcelbraghini
#
#networks:
#  marcelbraghini:
#    driver: bridge