openapi: 3.0.1
info:
  title: OpenAPI for quarkus rest
  description: Documentation for quarkus rest
  version: "1.0.0"

servers:
  - url: http://localhost:8080/
    description: Optional dev mode server description

paths:
  /v1/users:
    get:
      description: Get all users
      responses:
        200:
          description: OK
          content:
            application/json: {}
    post:
      description: Create new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: Created
          content:
            application/json: {}
        400:
          description: Bad Request
          content:
            application/json: {}
  /v1/users/{_id}:
    get:
      description: Get a user
      responses:
        200:
          description: OK
          content:
            application/json: {}
        404:
          description: Not Found
          content:
            application/json: {}
    put:
      description: Put a user
      responses:
        200:
          description: OK
          content:
            application/json: {}
        404:
          description: Not Found
    delete:
      description: Delete a user
      responses:
        200:
          description: OK
        404:
          description: Not Found

components:
  schemas:
    User:
      properties:
        login:
          type: string
        name:
          type: string
        blog:
          type: string
        location:
          type: string
        bio:
          type: string